# Generated by Django 4.2.16 on 2024-11-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0002_alter_time_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='name',
            field=models.TimeField(max_length=255),
        ),
    ]
